export const SET_REGISTER_INDEX_DATA = 'SET_REGISTER_INDEX_DATA';
export const CLEAR_REGISTER_INDEX_DATA = 'CLEAR_REGISTER_INDEX_DATA';
export const UPDATE_REGISTER_INDEX_DATA = 'UPDATE_REGISTER_INDEX_DATA';
export const LOAD_REGISTER_INDEX_DATA = 'LOAD_REGISTER_INDEX_DATA';